apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: moyinoluwaadenuga/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: udagram-env-secret
          - configMapRef:
              name: udagram-env-config
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: udagram-aws-secret
      volumes:
        - name: udagram-aws-secret
          configMap:
            name: udagram-aws-secret
