apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: moyinoluwaadenuga/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: udagram-env-secret
          - configMapRef:
              name: udagram-env-config
